import Head from 'next/head'
import { Inter } from '@next/font/google'
import React, { useRef, useState } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/effect-cards";
import { EffectCards } from "swiper";
import { PrismaClient } from '@prisma/client'
import { GiGemini } from 'react-icons/gi'
const inter = Inter({ subsets: ['latin'] })





export default function Home({veterans}) {
  return (
    <>
      <Head>
        <title>Adote Um calouro!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black">
      <div className=" h-[100vh] p-5">
      <Swiper
        effect={"cards"}
        modules={[EffectCards]}
        className="h-[600px] w-full"
        
      >
        {veterans.map((veteran) => {
        return <SwiperSlide
        className="bg-slate-900 rounded-3xl"
        key={veteran.id}
        >
          <div className="h-full flex justify-start items-end pl-5 pb-5" style={{backgroundImage: `url(${veteran.profilePicture})`, backgroundSize:"cover", backgroundPosition: "center"}}>
            
            <div className="block">
            <GiGemini className="text-white text-4xl"/>
            <h1 className="text-3xl text-white">{veteran.name}</h1>
            <h2 className="text-2xl text-white">{veteran.bio}</h2>
            </div>
          </div>
          
        </SwiperSlide>;
      })}
      </Swiper>
      <h3 className="text-white text-xl">Marque os veteranos que, julgando pelo que você leu, gostaria que te adotasse.</h3>
      </div>
      </main>
      
    </>
  )
}

export async function getServerSideProps() {
  const prisma = new PrismaClient()
  return {
    props: {
      veterans: await prisma.veteran.findMany(),
    },
  }
}

